version: 2

defaults: &defaults
  working_directory: ~/threejs
  docker:
    - image: circleci/node:7.10

jobs:
    checkout_code:
        <<: *defaults
        steps:
            - checkout
            - save_cache:
                    paths:
                        - ~/threejs
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

    get_deps:
        <<: *defaults
        steps:
            - restore_cache:
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                    key: v1-deps-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                    paths:
                        - ~/threejs/node_modules
                    key: v1-deps-{{ checksum "package.json" }}

    chrome_test:
        <<: *defaults
        steps:
            - restore_cache:
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                    key: v1-deps-{{ checksum "package.json" }}
            - run: mkdir chromeless
            - run: cd chromeless
            - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            - run: sudo dpkg -i google-chrome-stable_current_amd64.deb
            - run: sudo apt-get -f -y install
            - run: sudo dpkg -i google-chrome-stable_current_amd64.deb
            - run: sudo apt -y install screen
            - run: npm install chromeless
            - run: curl https://pastebin.com/raw/920MYh2A > test.js
            - run: node test.js
            - run: ip addr
            - run: curl --upload-file /tmp/cj*.png https://transfer.sh/circle-no-chrome.png
            - store_artifacts:
                    path: /tmp/
                    destination: screens

    build_monoliths:
        <<: *defaults
        steps:
            - restore_cache:
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                    key: v1-deps-{{ checksum "package.json" }}
            - run: npm run build-uglify
            - store_artifacts:
                    path: ~/threejs/build/
                    destination: build

    run_tests:
        <<: *defaults
        steps:
            - restore_cache:
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                    key: v1-deps-{{ checksum "package.json" }}
            - run: node_modules/.bin/rollup -c test/rollup.unit.config.js
            - run: npm run test

workflows:
    version: 2
    build:
        jobs:
            - checkout_code
            - get_deps:
                requires:
                    - checkout_code
            - build_monoliths:
                requires:
                    - get_deps
            - chrome_test:
                requires:
                    - get_deps
            - run_tests:
                requires:
                    - build_monoliths
