version: 2

defaults: &defaults
  working_directory: ~/threejs
  docker:
    - image: circleci/node:7.10

jobs:
    checkout_code:
        <<: *defaults
        steps:
            - checkout
            - save_cache:
                    paths:
                        - ~/threejs
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

    get_deps:
        <<: *defaults
        steps:
            - restore_cache:
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                    key: v1-deps-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                    paths:
                        - ~/threejs/node_modules
                    key: v1-deps-{{ checksum "package.json" }}

    build_monoliths:
        <<: *defaults
        steps:
            - restore_cache:
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                    key: v1-deps-{{ checksum "package.json" }}
            - run: npm run build-uglify
            - store_artifacts:
                    path: ~/threejs/build/
                    destination: build

    run_tests:
        <<: *defaults
        steps:
            - restore_cache:
                    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                    key: v1-deps-{{ checksum "package.json" }}
            - run: node_modules/.bin/rollup -c test/rollup.unit.config.js
            - run: npm run test

workflows:
    version: 2
    build:
        jobs:
            - checkout_code
            - get_deps:
                requires:
                    - checkout_code
            - build_monoliths:
                requires:
                    - get_deps
            - run_tests:
                requires:
                    - build_monoliths
